# Generated by Django 2.2.6 on 2019-11-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='catagory',
            field=models.CharField(choices=[('GP', 'Google PLay'), ('AM', 'AMAZON'), ('NF', 'NETFLIX'), ('IT', 'ITUNES'), ('ST', 'STEAM')], default='GP', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
