# Generated by Django 2.2.6 on 2019-11-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsite', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a dummy description'),
            preserve_default=False,
        ),
    ]
