# Generated by Django 2.2.6 on 2019-11-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsite', '0008_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
