# Generated by Django 2.2.6 on 2019-11-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsite', '0010_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
