# Generated by Django 2.2.6 on 2019-11-10 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardsite', '0014_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('percent', models.IntegerField()),
                ('lessen', models.IntegerField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('oneuse', models.BooleanField(default=True)),
                ('used_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardsite.Coupon'),
        ),
    ]
