# Generated by Django 2.2.6 on 2019-11-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardsite', '0016_auto_20191111_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='giftCard',
            new_name='gift_cards',
        ),
    ]
