# Generated by Django 2.2.6 on 2019-11-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsite', '0017_auto_20191111_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AddField(
            model_name='item',
            name='iscode',
            field=models.BooleanField(default=True),
        ),
    ]
