# Generated by Django 2.2.6 on 2019-11-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsite', '0018_auto_20191111_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=10)),
            ],
        ),
    ]
