# Generated by Django 2.2.6 on 2019-11-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsite', '0020_auto_20191111_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
